# ----
# Site

title: investessex.co.uk
url: "https://honeydew-pooch.cloudvent.net"
baseurl: 
google_analytics_key:
google_maps_javascript_api_key:
cdn_images: '//clarity-strategies.github.io/ie-uploads/uploads'
postal-address: 'Suite 8C, Kingsdale Business Centre, Regina Road, Chelmsford. CM1 1PE'

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)



# -----
# Build

permalink: /blog/:title

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate-v2
  - algoliasearch-jekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - _off
#  - _partner-companies

collections:
  case-studies:
    output: true
    permalink: /studies/case-studies/:path
  case-studies-leading-companies:
    output: true
    permalink: /studies/case-studies/:path
  place-studies:
    output: true
    permalink: /studies/place-studies/:path
  sectors:
    output: true
    permalink: /sectors/:path
  contacts:
    output: true
    permalink: /contacts/:path
  events:
    output: false
    permalink: /events/:path
  invest-essex-events:
    output: false
    permalink: /invest-essex-events/:path
  partner-sectors:
    output: true
    permalink: /partner-sectors/:path
  partner-companies:
    output: true
    permalink: /partner-companies/:path

  

#paginate: 10
#paginate_path: "/blog/page:num/"
pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true


jekyll-archives:
  enabled: ['categories','tags']
  layouts:
  year: year-archive
  month: month-archive
  day: day-archive
  category: category-archive-layout
  tag: tag-archive-layout
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
    #year: '/:year/'
    #month: '/:year/:month/'
    #day: '/:year/:month/:day/'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# -----------
# CloudCannon
_editable_regions:
  image:
    url_src: true

#---------------
# algolia search
#---------------
#algolia:
#  application_id: '4UTC2BOCJR'
#  index_name:     'IE_search'

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
